### PR TITLE
fix file-system dependency issue

### PR DESCRIPTION
**Pull request by bishoymelek-zz**
I tried to install the module using command line but the app crashed because "file-system" dependency

1. It wasn't installed because It wasn't listed in the dependencies list in package.json .
2. It was calling (file-system/file-system-access) but I found that only calling (file-system) is enough.

Please let me know what do you think ?

Thanks a lot

### CODE REVIEW

**Comment by NathanaelA** [comment]
Well, I can tell you this will fail.   But I really do appreciate the pull request!!!

The `file-system/file-system-access` is a file that is part of the NativeScript core modules and is already installed in a NativeScript application, so no extra dependencies are required.    Adding "file-system" to the dependencies is going to give you something that won't work on NativeScript as that particular `file-system` was written for Node.     :grinning:    

Now as to your crash; are you by any chance using Webpack?     If so then I know the solution, and I do need to make the change to the file as I've seen reports that the new version of Webpack requires slightly differently than the older versions.  

The require line should be changed to 
```
const FileSystemAccess = require('tns-core-modules/file-system/file-system-access').FileSystemAccess;
```

**Comment by bishoymelek-zz** [comment]
Thanks Boss for your reply! I don't know why this didn't work for me
I had to make it as follows:
const FileSystemAccess = require(
'../tns-core-modules/file-system/file-system-access.d').FileSystemAccess;

**Comment by bishoymelek-zz** [comment]
@NathanaelA this is what worked for me at the end ... I don't know if it's good enough or not .. but It's working .. can you please tell me your opinion ?

**Comment by NathanaelA** [comment]
What you did shouldn't actually work.    The only change I believe to allow webpack to work is:
```
const FileSystemAccess = require('tns-core-modules/file-system/file-system-access').FileSystemAccess;
```

**Comment by bishoymelek-zz** [comment]
nop as I told you it gives an error as well :( 
Module not found: Error: Can't resolve 'tns-core-modules/file-system/file-system-access' in '~/angular-native-seed/node_modules/nativescript-localstorage'
Do you know the fix for this please ?

**Comment by NathanaelA** [comment]
I'll be releasing a new version of this later today that has been tested with the latest version of NativeScript.   I just tested the fix I listed above, and it worked for me in a standard app and a webpacked app.  

However, looking at your message it looking like you are using the angular-native-seed -- the native-seed is no longer maintained and probably where the issue is at...   You would need to change the webpack rules.   I would highly recommend you switch to xplat as it is the next generation of the seed and is well maintained.

**Comment by NathanaelA** [comment]
I have tested the new v2.0 (which I just released) of NS-Localstorage in webpack and it works fine.

**Pull request closed without merging**
