### PR TITLE
Solved problem with webpack uglify

### PR DESCRIPTION
**Pull request by jibon57**
This will resolve the problem with webpack uglify.

### CODE REVIEW

**Comment by cboisen** [comment]
I was just about to file a similar pull request! 👍

**Review by smarza — APPROVED** [review]
Works.

**Comment by NathanaelA** [comment]
See: https://github.com/NathanaelA/nativescript-localstorage/issues/10

**Comment by smarza** [comment]
@NathanaelA 

Totally agree.
Thanks

**Comment by dungfv** [comment]
please merge to master, soon! i'm expecting that

**Comment by NathanaelA** [comment]
This issue should no longer be happening -- I'm pretty sure they have upgraded the webpack to use the new uglify-es6 branch...

**Comment by darkylmnx** [comment]
@NathanaelA still not working in a fresh nativescript project made today

**Comment by NathanaelA** [comment]
Just a FYI; I just tested this in the latest version of WebPack and it works.

**Pull request closed without merging**
